# Generated by Django 2.2 on 2020-01-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200108_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invitation_code',
            field=models.CharField(default='', max_length=128),
        ),
    ]
